{% import "autoAPI/ir/dockerfile" %}

{% func Render(dockerfile dockerfile.Dockerfile) %}
FROM golang:1.15-alpine as builder
RUN apk add git
COPY . /go/src/{%v dockerfile.Name.CamelCase() %}
ENV GO111MODULE on
WORKDIR /go/src/{%v dockerfile.Name.CamelCase() %}
RUN go mod tidy && go build

FROM alpine
COPY --from=builder /go/src/{%v dockerfile.Name.CamelCase() %}/{%v dockerfile.Name.CamelCase() %} /
WORKDIR /
CMD ./{%v dockerfile.Name.CamelCase() %}
EXPOSE 8000
{% endfunc %}
