name: Integration test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Run smoke test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: make build
      - name: Run the test case
        run: ./integration/smoke/run.sh
  basic_crud:
    needs: smoke_test
    runs-on: ubuntu-latest
    name: Run basic crud test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Init database
        uses: docker://migrate/migrate
        with:
          args:
            -database "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable" -path integration/basic-crud/migration/postgres up
      - name: Build
        run: make build
      - name: Run the test case
        run: python3 ./integration/basic-crud/test.py ./integration/basic-crud/golang/postgres.yml
        env:
          DB_ADDRESS: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  basic_crud_mysql:
    needs: smoke_test
    runs-on: ubuntu-latest
    name: Run basic crud for mysql
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=15s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Init database
        uses: docker://migrate/migrate
        with:
          args:
            -database "mysql://user:password@tcp(mysql:3306)/database" -path integration/basic-crud/migration/mysql up
      - name: Build
        run: make build
      - name: Run the test case
        run: python3 ./integration/basic-crud/test.py ./integration/basic-crud/golang/mysql.yml
        env:
          DB_ADDRESS: user:password@tcp(localhost:3306)/database?allowCleartextPasswords=true&allowNativePasswords=true&parseTime=true
  non_interger_pk:
    needs: basic_crud
    runs-on: ubuntu-latest
    name: Run basic crud when id is not an integer
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Init database
        uses: docker://migrate/migrate
        with:
          args:
            -database "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable" -path integration/non-integer-pk/migration/postgres up
      - name: Build
        run: make build
      - name: Run the test case
        run: python3 ./integration/non-integer-pk/test.py ./integration/non-integer-pk/golang/postgres.yml
        env:
          DB_ADDRESS: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  non_interger_pk_mysql:
    needs: basic_crud_mysql
    runs-on: ubuntu-latest
    name: Run basic crud when id is not an integer for mysql
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=15s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Init database
        uses: docker://migrate/migrate
        with:
          args:
            -database "mysql://user:password@tcp(mysql:3306)/database" -path integration/non-integer-pk/migration/mysql up
      - name: Build
        run: make build
      - name: Run the test case
        run: python3 ./integration/non-integer-pk/test.py ./integration/non-integer-pk/golang/mysql.yml
        env:
          DB_ADDRESS: user:password@tcp(localhost:3306)/database?allowCleartextPasswords=true&allowNativePasswords=true&parseTime=true
  docker:
    needs: smoke_test
    runs-on: ubuntu-latest
    name: Run generating docker test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: make build
      - name: Run the test case
        run: python3 ./integration/docker/test.py
  cicd:
    needs: smoke_test
    runs-on: ubuntu-latest
    name: Run generating cicd test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: make build
      - name: Run the test case
        run: python3 ./integration/cicd/test.py