name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
# todo: integration tests
